version: 2.1

orbs:
  win: circleci/windows@2.2.0
  codecov: codecov/codecov@1.0.2

jobs:
  build:
    executor: win/default     
    
    steps:
      - checkout
      - run: dotnet restore SimpleWebAPI
      - run: dotnet build SimpleWebAPI
      - run: dotnet test SimpleWebAPI/SimpleWebAPI.Test/SimpleWebAPI.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=lcov
      - codecov/upload:
          file: SimpleWebAPI/SimpleWebAPI.Test